In [3]:
import convolve
import numpy as np
import time

In [4]:
dim_a_1 = 1000
dim_a_2 = 9
a_1 = np.arange(dim_a_1 ** 2, dtype=float).reshape((dim_a_1, dim_a_1))
a_2 = np.arange(dim_a_2 ** 2, dtype=float).reshape((dim_a_2, dim_a_2))

# a_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
# a_2 = np.array([[1, 2], [3, 4]], dtype=float)
print(a_1)
print(a_2)
padding = 1
stride = 1
dim_out = (a_1.shape[0] - a_2.shape[0] + 2 * padding) // stride + 1
a_out = np.zeros((dim_out, dim_out), dtype=float)
a_1 = a_1.reshape((a_1.shape[0] * a_1.shape[1],))
a_2 = a_2.reshape((a_2.shape[0] * a_2.shape[1],))
a_out = a_out.reshape((dim_out ** 2,))
start = time.clock()
convolve.convolve2D(a_1, a_2, dim_a_1, dim_a_2, padding, stride, a_out)
print(time.clock() - start)
print(a_out.reshape((dim_out, dim_out)))

[[  0.00000000e+00   1.00000000e+00   2.00000000e+00 ...,   9.97000000e+02
    9.98000000e+02   9.99000000e+02]
 [  1.00000000e+03   1.00100000e+03   1.00200000e+03 ...,   1.99700000e+03
    1.99800000e+03   1.99900000e+03]
 [  2.00000000e+03   2.00100000e+03   2.00200000e+03 ...,   2.99700000e+03
    2.99800000e+03   2.99900000e+03]
 ..., 
 [  9.97000000e+05   9.97001000e+05   9.97002000e+05 ...,   9.97997000e+05
    9.97998000e+05   9.97999000e+05]
 [  9.98000000e+05   9.98001000e+05   9.98002000e+05 ...,   9.98997000e+05
    9.98998000e+05   9.98999000e+05]
 [  9.99000000e+05   9.99001000e+05   9.99002000e+05 ...,   9.99997000e+05
    9.99998000e+05   9.99999000e+05]]
[[  0.   1.   2.   3.   4.   5.   6.   7.   8.]
 [  9.  10.  11.  12.  13.  14.  15.  16.  17.]
 [ 18.  19.  20.  21.  22.  23.  24.  25.  26.]
 [ 27.  28.  29.  30.  31.  32.  33.  34.  35.]
 [ 36.  37.  38.  39.  40.  41.  42.  43.  44.]
 [ 45.  46.  47.  48.  49.  50.  51.  52.  53.]
 [ 54.  55.  56.  57.  58.  59. 